services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: university_portal
      POSTGRES_USER: django_admin
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U django_admin -d university_portal"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: 
      context: .
      args:
        PIP_TIMEOUT: "300"

    command: >
      sh -c "python manage.py migrate &&
             gunicorn university_portal.wsgi:application --bind 0.0.0.0:$PORT"
    environment:
      DB_HOST: db
      DB_NAME: university_portal
      DB_USER: django_admin
      DB_PASSWORD: postgres
      DEBUG: "False"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    # Removed command since it's now in Dockerfile

volumes:
  postgres_data: